class NodeQuery[T]
  VERSION: String

  def self.configure: (options: { adapter: NodeQuery::Adapter }) -> void

  def self.adapter: () -> NodeQuery::Adapter

  def initialize: (nqlOrRues: String | Hash) -> NodeQuery

  def query_nodes: (node: T, options: Hash) -> Array[T]

  def match_node?: (node: T) -> boolean
end
