class NodeQuery[T]
  VERSION: String

  def initialize: (nqlOrRues: String | Hash, adapter: NodeQuery::Adapter) -> NodeQuery

  def query_nodes: (node: T, options: Hash) -> Array[T]

  def match_node?: (node: T) -> boolean
end
