class NodeQuery::Adapter[T]
  def is_node?: (node: T) -> bool

  def get_node_type: (node: T) -> String

  def get_source: (node: T) -> String

  def get_children: (node: T) -> Array[T]

  def get_siblings: (node: T) -> Array[T]
end
